<a href="https://colab.research.google.com/github/IqmanS/summer_school_assignments/blob/main/Assignment_2_Advance_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import string
import random
import os
import pandas as pd
!pip install google_images_download
from google_images_download import google_images_download

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: google_images_download in /usr/local/lib/python3.10/dist-packages (2.8.0)
Requirement already satisfied: selenium in /usr/local/lib/python3.10/dist-packages (from google_images_download) (4.10.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in /usr/local/lib/python3.10/dist-packages (from selenium->google_images_download) (1.26.15)
Requirement already satisfied: trio~=0.17 in /usr/local/lib/python3.10/dist-packages (from selenium->google_images_download) (0.22.0)
Requirement already satisfied: trio-websocket~=0.9 in /usr/local/lib/python3.10/dist-packages (from selenium->google_images_download) (0.10.3)
Requirement already satisfied: certifi>=2021.10.8 in /usr/local/lib/python3.10/dist-packages (from selenium->google_images_download) (2022.12.7)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium->google_images_download) (23.1.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium->google_images_download) (2.4.0)
Requirement already satisfied: async-generator>=1.9 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium->google_images_download) (1.10)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium->google_images_download) (3.4)
Requirement already satisfied: outcome in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium->google_images_download) (1.2.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium->google_images_download) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium->google_images_download) (1.1.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.10/dist-packages (from trio-websocket~=0.9->selenium->google_images_download) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from urllib3[socks]<3,>=1.26->selenium->google_images_download) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium->google_images_download) (0.14.0)

# Part I: Process Automation
---
1. Create a file that contains 1000 lines of random strings.
2. Create a file that contains multiple lines of random strings and file size must be 5 MB.
3. Create 10 files that contains multiple lines of random strings and file size of each file must be 5 MB.
4. Create 5 files of size 1GB, 2GB, 3GB, 4GB and 5GB; file contains multiple lines of random strings.
5. Convert all the files of Q4 into upper case one by one.
6. Convert all the files of Q4 into upper case parallel using multi-threading.
7. WAP to automatically download 10 images of cat from “Google Images”. [Hint: Find the package from
pypi.org and use it]
8. WAP to automatically download 10 videos of “Machine Learning” from “Youtube.com”. [Hint: Find the
package from pypi.org and use it]
9. Convert all the videos of Q8 and convert it to audio. [Hint: Find the package from pypi.org and use it]
10. Create an automated pipeline using multi-threading for:
“Automatic Download of 100 Videos from YouTube” → “Convert it to Audio”.
11. Create an automated pipeline using multi-threading for: “Automatic Download of 500 images of Dog from
GoogleImages” → “Rescale it to 50%”.

In [ ]:
f = open("file1.txt","w")
for i in range(1000):
  s = random.choices(population=string.ascii_lowercase,k=random.randint(5,10))
  s = "".join(s)
  f.write(s)
  f.write("\n")
f.close()

In [ ]:
limit = 5*1024*1024 #bytes
f = open("file2.txt","w")
size = os.path.getsize("/content/file2.txt")
while size<limit:
  size = os.path.getsize("/content/file2.txt")
  s = random.choices(population=string.ascii_lowercase,k=random.randint(5,10))
  s="".join(s)
  f.write(s)
  f.write("\n")
f.close()

In [ ]:
response = google_images_download.googleimagesdownload()   #class instantiation

arguments = {"keywords":"cats","limit":10,"print_urls":True}   
paths = response.download(arguments)   
print(paths)

Item no.: 1 --> Item name = Polar bears
Evaluating...
Starting Download...


Unfortunately all 10 could not be downloaded because some images were not downloadable. 0 is all we got for this search filter!

Errors: 0


Item no.: 2 --> Item name = baloons
Evaluating...
Starting Download...


Unfortunately all 10 could not be downloaded because some images were not downloadable. 0 is all we got for this search filter!

Errors: 0

({'Polar bears': [], 'baloons': []}, 0)

# Part II: Data Analytics
---
12. Create a random dataset of 100 rows and 30 columns. All the values are defined between [1,200]. Perform
the following operations:
 1. Replace all the values with NA in the dataset defined between [10, 60]. Print the count of number
rows having missing values.
 2. Replace all the NA values with the average of the column value.
 3. Find the Pearson correlation among all the columns and plot heat map. Also select those columns
having correlation <=0.7.
 4. Normalize all the values in the dataset between 0 and 10.
 5. Replace all the values in the dataset with 1 if value <=0.5 else with 0.
13. Create a random dataset of 500 rows and 10 columns.<br>
    Columns 1 to 4 are defined between [-10, 10] <br>
  Columns 5 to 8 are defined between [10, 20] <br>
  Columns 9 to 10 are defined between [-100, 100].<br>
Apply following clustering algorithms; determine the optimal number of clusters and plot distance metric graph using each algorithm.
 1. K-Mean clustering
 2. Hierarchical clustering
14. Create a random dataset of 600 rows and 15 columns. All the values are defined between [-100,100].<br>
Perform the following operations:
 1. Plot scatter graph between Column 5 and Column 6.
 2. Plot histogram of each column in single graph.
 3. Plot the Box plot of each column in single graph.
15. Create a random dataset of 500 rows and 5 columns:
All the values are defined between [5,10].<br>
Perform the following operations:
 1. Perform t-Test on each column.
 2. Perform Wilcoxon Signed Rank Test on each column.
 3. Perform Two Sample t-Test and Wilcoxon Rank Sum Test on Column 3 and Column 4

In [ ]:
df1 = pd.DataFrame(np.random.randn(100,30))
df1.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,-0.516992,0.574873,-0.230242,0.233160,0.147305,-0.036048,-1.860900,-0.289677,0.299228,-0.830363,...,0.385326,-0.934660,0.066702,-0.838680,0.249426,-0.995536,0.148469,-1.548690,-0.993609,-0.500182
1,-1.290804,-1.498306,-0.390752,1.175158,0.933970,0.742146,-2.236082,0.867564,-1.046490,-0.957504,...,-1.869334,2.618841,-0.542808,0.576738,0.603061,2.471884,-1.551595,-0.525186,-1.401146,-1.642223
2,1.292842,1.673626,1.251489,0.163252,-0.830563,0.733731,-0.160632,0.309260,0.156108,0.603646,...,-0.008256,0.736449,1.436250,1.952298,1.424928,-1.647236,-0.750011,1.028034,0.976729,-1.056543
3,1.710163,1.249633,0.710065,0.893038,1.712068,-0.626852,0.179481,1.355080,0.983596,0.253962,...,-0.587678,0.237877,0.748472,1.903593,0.472629,0.981270,0.390027,0.724376,-1.056377,1.513590
4,1.097661,2.057417,-2.822115,-0.077287,0.693692,0.087347,1.323641,1.109424,-0.361995,0.189400,...,-0.770624,-1.703713,-0.894353,-0.203017,2.133861,-0.161977,-0.992422,1.224826,-1.804307,0.310196